set(LIBDXL_PATH "${CMAKE_SOURCE_DIR}/src" CACHE PATH "Path to the libdxl library")
#MESSAGE(STATUS "CMAKE_DIR2: " ${CMAKE_SOURCE_DIR})
MESSAGE(STATUS "LIBDXL_PATH: " ${LIBDXL_PATH})

#find_path(OpenMRL_INCLUDE_DIRS NAMES config.h HINTS ${OpenMRL_PATH}/src)
#MESSAGE(STATUS "OpenMRL_INCLUDE_DIRS: " ${OpenMRL_INCLUDE_DIRS})

#FIND_LIBRARY(TCL_LIB NAMES dxl PATHS /home/raul/fuerte_workspace/dynamixel/src)
find_library(LIBDXL_LIBRARIES NAMES dxl PATHS ${LIBDXL_PATH})
MESSAGE(STATUS "LIBDXL_LIBRARIES: " ${LIBDXL_LIBRARIES})

set(DXL_FOUND FALSE)

#IF(OpenMRL_INCLUDE_DIRS AND OpenMRL_LIBRARIES)
     #SET(MRL_FOUND TRUE)
#ENDIF(OpenMRL_INCLUDE_DIRS AND OpenMRL_LIBRARIES)
